-- init.sql
CREATE TABLE IF NOT EXISTS raw_data (
    id SERIAL PRIMARY KEY,
    depth FLOAT,
    hole_depth FLOAT,
    bit_depth FLOAT,
    inclination FLOAT,
    azimuth FLOAT,
    dogleg_severity FLOAT,
    annulus_pressure FLOAT,
    standpipe_pressure FLOAT,
    bottomhole_pressure FLOAT,
    pore_pressure FLOAT,
    mud_pressure FLOAT,
    pressure_diff FLOAT,
    bottomhole_temp FLOAT,
    mud_temp_in FLOAT,
    mud_temp_out FLOAT,
    temp_diff FLOAT,
    weight_on_bit FLOAT,
    torque FLOAT,
    rotary_speed FLOAT,
    rate_of_penetration FLOAT,
    flow_rate FLOAT,
    pump_pressure FLOAT,
    mud_density FLOAT,
    mud_viscosity FLOAT,
    mud_ph FLOAT,
    chloride_content FLOAT,
    solids_content FLOAT,
    mud_rheology FLOAT,
    filter_cake_thickness FLOAT,
    gamma_ray FLOAT,
    resistivity FLOAT,
    neutron_porosity FLOAT,
    density_porosity FLOAT,
    sonic_slowness FLOAT,
    permeability_index FLOAT,
    vibration_x FLOAT,
    vibration_y FLOAT,
    vibration_z FLOAT,
    shock FLOAT,
    hook_load FLOAT,
    block_position FLOAT,
    pump_stroke FLOAT,
    total_gas FLOAT,
    c1_gas FLOAT,
    c2_gas FLOAT,
    co2_content FLOAT,
    h2s_content FLOAT,
    skin_factor FLOAT,
    productivity_index FLOAT,
    injectivity_index FLOAT,
    damage_ratio FLOAT,
    equipment_status TEXT,
    battery_voltage FLOAT,
    internal_temp FLOAT,
    vibration_level FLOAT,
    pressure_alarm TEXT,
    temperature_alarm TEXT,
    gas_alarm TEXT,
    drilling_phase JSONB,
    damage_event TEXT,
    retention_tier TEXT,
    data_quality_score FLOAT,
    formation_type TEXT,
    lithology TEXT,
    damage_risk_score FLOAT,
    rpm FLOAT,
    ecd FLOAT,
    field_name TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS raw_data (
    depth DECIMAL,
    hole_depth DECIMAL,
    bit_depth DECIMAL,
    inclination DECIMAL,
    azimuth DECIMAL,
    dogleg_severity DECIMAL,
    annulus_pressure DECIMAL,
    standpipe_pressure DECIMAL,
    bottomhole_pressure DECIMAL,
    pore_pressure DECIMAL,
    mud_pressure DECIMAL,
    pressure_diff DECIMAL,
    bottomhole_temp DECIMAL,
    mud_temp_in DECIMAL,
    mud_temp_out DECIMAL,
    temp_diff DECIMAL,
    weight_on_bit DECIMAL,
    torque DECIMAL,
    rotary_speed DECIMAL,
    rate_of_penetration DECIMAL,
    flow_rate DECIMAL,
    pump_pressure DECIMAL,
    mud_density DECIMAL,
    mud_viscosity DECIMAL,
    mud_ph DECIMAL,
    chloride_content DECIMAL,
    solids_content DECIMAL,
    mud_rheology DECIMAL,
    filter_cake_thickness DECIMAL,
    gamma_ray DECIMAL,
    resistivity DECIMAL,
    neutron_porosity DECIMAL,
    density_porosity DECIMAL,
    sonic_slowness DECIMAL,
    permeability_index DECIMAL,
    vibration_x DECIMAL,
    vibration_y DECIMAL,
    vibration_z DECIMAL,
    shock DECIMAL,
    hook_load DECIMAL,
    block_position DECIMAL,
    pump_stroke DECIMAL,
    total_gas DECIMAL,
    c1_gas DECIMAL,
    c2_gas DECIMAL,
    co2_content DECIMAL,
    h2s_content DECIMAL,
    skin_factor DECIMAL,
    productivity_index DECIMAL,
    injectivity_index DECIMAL,
    damage_ratio DECIMAL,
    timestamp TIMESTAMPTZ,
    equipment_status VARCHAR(50),
    battery_voltage DECIMAL,
    internal_temp DECIMAL,
    vibration_level DECIMAL,
    pressure_alarm VARCHAR(50),
    temperature_alarm VARCHAR(50),
    gas_alarm VARCHAR(50),
    drilling_phase TEXT,
    damage_event TEXT,
    retention_tier VARCHAR(50),
    data_quality_score DECIMAL,
    formation_type VARCHAR(50),
    lithology VARCHAR(50),
    damage_risk_score DECIMAL
);
ALTER TABLE raw_data ADD COLUMN RPM FLOAT;
ALTER TABLE raw_data ADD COLUMN ECD FLOAT;
-- well_measurements table
ALTER TABLE well_measurements ADD COLUMN is_valid BOOLEAN DEFAULT TRUE;
CREATE TABLE IF NOT EXISTS well_measurements (
    measurement_id UUID PRIMARY KEY,
    well_id VARCHAR(50) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    depth DECIMAL(10, 2),
    mud_type VARCHAR(20),
    rpm INTEGER,
    spp DECIMAL(10, 2),
    flow_rate DECIMAL(10, 2),
    viscosity DECIMAL(10, 2),
    temperature DECIMAL(10, 2),
    ecd DECIMAL(10, 2),
    shale_content DECIMAL(5, 2),
    lithology VARCHAR(50),
    ph DECIMAL(4, 2),
    cl_concentration DECIMAL(10, 2),
    oil_water_ratio DECIMAL(5, 2),
    is_anomaly BOOLEAN DEFAULT FALSE,
    damage_type_prediction VARCHAR(50),
    prediction_confidence DECIMAL(5, 4),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- damage_types table
CREATE TABLE IF NOT EXISTS damage_types (
    damage_type_id VARCHAR(10) PRIMARY KEY,
    damage_name VARCHAR(100) NOT NULL,
    description TEXT,
    severity_level INTEGER,
    common_causes TEXT[],
    mitigation_strategies TEXT[]
);
