-- Table: damage_types
CREATE TABLE damage_types (
    damage_type_id VARCHAR(10) PRIMARY KEY,
    damage_name VARCHAR(50) NOT NULL
);
-- Table: well_measurements
CREATE TABLE well_measurements (
    measurement_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    timestamp TIMESTAMP(3) NOT NULL,
    depth DECIMAL(10,2),
    hole_depth DECIMAL(10,2),
    bit_depth DECIMAL(10,2),
    inclination DECIMAL(5,2),
    azimuth DECIMAL(5,2),
    dogleg_severity DECIMAL(5,2),
    annulus_pressure DECIMAL(10,2),
    standpipe_pressure DECIMAL(10,2),
    bottomhole_pressure DECIMAL(10,2),
    pore_pressure DECIMAL(10,2),
    mud_pressure DECIMAL(10,2),
    pressure_diff DECIMAL(10,2),
    bottomhole_temp DECIMAL(5,2),
    mud_temp_in DECIMAL(5,2),
    mud_temp_out DECIMAL(5,2),
    temp_diff DECIMAL(5,2),
    weight_on_bit DECIMAL(5,2),
    torque DECIMAL(5,2),
    rotary_speed DECIMAL(5,2),
    rate_of_penetration DECIMAL(5,2),
    flow_rate DECIMAL(10,2),
    pump_pressure DECIMAL(10,2),
    mud_density DECIMAL(5,2),
    mud_viscosity DECIMAL(5,2),
    mud_ph DECIMAL(4,2),
    chloride_content DECIMAL(10,2),
    solids_content DECIMAL(5,2),
    mud_rheology DECIMAL(5,2),
    filter_cake_thickness DECIMAL(5,2),
    gamma_ray DECIMAL(5,2),
    resistivity DECIMAL(10,2),
    neutron_porosity DECIMAL(5,3),
    density_porosity DECIMAL(5,3),
    sonic_slowness DECIMAL(5,2),
    permeability_index DECIMAL(10,2),
    vibration_x DECIMAL(5,2),
    vibration_y DECIMAL(5,2),
    vibration_z DECIMAL(5,2),
    shock DECIMAL(5,2),
    hook_load DECIMAL(10,2),
    block_position DECIMAL(5,2),
    pump_stroke DECIMAL(5,2),
    total_gas DECIMAL(5,2),
    c1_gas DECIMAL(5,2),
    c2_gas DECIMAL(5,2),
    co2_content DECIMAL(5,2),
    h2s_content DECIMAL(5,3),
    skin_factor DECIMAL(5,2),
    productivity_index DECIMAL(5,2),
    injectivity_index DECIMAL(5,2),
    damage_ratio DECIMAL(5,2)
);
