apiVersion: 1

datasources:
  # PostgreSQL datasource for operational data
  - name: PostgreSQL-FIDPS
    type: postgres
    access: proxy
    url: postgres:5432
    database: fidps_operational
    user: fidps_user
    secureJsonData:
      password: fidps_password_2024
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1300
      timescaledb: true
    isDefault: true
    editable: true

  # Prometheus datasource for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 5s
      queryTimeout: 60s
      httpMethod: POST

  # MongoDB datasource for anomaly data (using JSON API plugin)
  - name: MongoDB-FIDPS
    type: grafana-mongodb-datasource
    access: proxy
    url: mongodb://mongo:27017
    database: fidps_anomalies
    user: root
    secureJsonData:
      password: fidps_mongo_password_2024
    isDefault: false
    editable: true
    jsonData:
      authSource: admin
      ssl: false

  # InfluxDB datasource for time-series metrics (if needed)
  - name: InfluxDB-FIDPS
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: fidps_metrics
    user: fidps_user
    secureJsonData:
      password: fidps_influx_password_2024
    isDefault: false
    editable: true
    jsonData:
      version: 1.8
      timeInterval: 10s
      httpMode: GET

  # Loki datasource for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60s

  # Elasticsearch datasource for log analytics
  - name: Elasticsearch-FIDPS
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: fidps-logs-*
    isDefault: false
    editable: true
    jsonData:
      interval: Daily
      timeField: '@timestamp'
      esVersion: 70
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level